export const TabNav = {
  Home: 'Home',
  FindADoctorHome: 'FindADoctorHome',
  Medicines: 'Medicines',
  ContactUs: 'ContactUs',
  AskVirtualVaidya: 'Ask Virtual Vaidya',
  
};

export const StackNav = {
  Splash: 'Splash',
  AuthStack: 'AuthStack',
  LoginScreen: 'LoginScreen',
  VerifyLoginOtp: 'VerifyLoginOtp',
  VerifyRegisterOtp: 'VerifyRegisterOtp',
  Signup: 'Signup',
  TabBar: 'TabBar',
  TabBarNew :'TabBarNew',
  FindADoctor:'Find A Doctor',
  DrawerNavigation: 'DrawerNavigation',
  TermsOfService: 'TermsOfService',
  PrivacyPolicy: 'PrivacyPolicy',
  CategoryDoctorListTab: 'CategoryDoctorListTab',
  CategoryDoctorList: 'CategoryDoctorList',
  CategoryDoctorListDrawer: 'CategoryDoctorListDrawer',
  DoctorProfile: 'DoctorProfile',
  PatientsReview: 'PatientsReview',
  PaymentScreen: 'PaymentScreen',
  SelectTimeSlot: 'SelectTimeSlot',
  InstantConsultation:'InstantConsultation',
  ClinicConsultation:'ClinicConsultation',
  ProductByCategoriesTab:'ProductByCategoriesTab',
  ProductByCategories:'ProductByCategories',
  ProductDetail:'ProductDetail',
  AppointmentBooked:'AppointmentBooked',
  AppointmentCancellation:'AppointmentCancellation',
  RescheduleAppointment:'RescheduleAppointment',
  ProductsReview:'ProductsReview',
  MedicineHome:'MedicineHome',
  Cart:'Cart',
  Address:'Address',
  OrderSummery:'OrderSummery',
  Appointments:'Appointments',
  LifeStyleDrawer:'LifeStyleDrawer',
  VideoCall : 'VideoCall',
  VideoCompleted : 'VideoCompleted',
  MyOrders : 'MyOrders',
  OrderDetails : 'OrderDetails',
  ProductsByBrand : 'ProductsByBrand',
  AboutUs : 'AboutUs',
  Profile : 'Profile',

};
